[package]
name = "android"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
edition = "2021"

[features]
default = []
autolink-libandroid = []

[dependencies]
libc = "0.2"
jni = "0.15"
